### ISSUE TITLE
重鼻炎的本质是鼻中隔弯曲，鼻腔气流结构出现了问题

### ISSUE THREAD

**Issue by zhulz** [i0Ek3/fuckit#2]

**Comment by i0Ek3** [comment]
那这个只能做手术了吧？
ps: 我 16 年的时候，本市三甲医院要求我做（应该是鼻窦引流）手术，但因为考研就拒绝了，后来也一直没做。
或许现在可以考虑一下了。

**Comment by zhulz** [comment]
最好不要做，鼻窦引流需要开鼻窦， 鼻中隔手术需要切掉一部分鼻中隔，可能会有后遗症
